spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Lms?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret:
    key: VGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1sb25nLXNlY3JldC1rZXktMTIzNDU2Nzg5MA
  expired:
    access: 3600000

server:
  port: 8081