spring:
  application:
    name: base_spring_boot

  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB

  datasource:
    url: jdbc:mysql://localhost:3306/lms_rikkei?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123456
    
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

  # TẠM THỜI TẮT REDIS
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  mail:
    host: smtp.gmail.com
    port: 587
    username: mankai.12.edu@gmail.com
    password: "xmsa ests sjji ftpl"  # 16 ký tự App Password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret:
    key: VGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1sb25nLXNlY3JldC1rZXktMTIzNDU2Nzg5MA
  expired:
    access: 3600000

server:
  port: 3900

app:
  upload:
    root: uploads
  notifications:
    sendOnAdminCreate: true

cloudinary:
  cloud-name: dhlngvmj5
  api-key: 451186165751151
  api-secret: YHZVyKDzQhp73vVM32iNj7ngYM4

external:
  api:
    base-url: https://example.com
    connect-timeout: 5000
    read-timeout: 10000


logging:
  level:
    "[org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsManagerConfigurer]": ERROR

payment:
  bank:
    id: "970407"                  # Mã ngân hàng VietQR của Techcombank
    account-no: "19021698833015"   # ⚠ Số tài khoản Techcombank của bạn
    account-name: "NGUYEN THI VAN"      # Tên chủ tài khoản (VIẾT HOA, không dấu)
    name: "Techcombank"           # Tên ngân hàng hiển thị
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
