spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://localhost:3306/lms_rikkie?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: /docs

jwt:
  secret:
    key: VGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1sb25nLXNlY3JldC1rZXktMTIzNDU2Nzg5MA
  expired:
    access: 3600000

server:
  port: 3999

external:
  api:
    base-url: https://example.com
    connect-timeout: 5000
    read-timeout: 10000
